import type { Metadata } from "next";
import "./globals.css";
import { OrganisationProvider } from "@/context/OrganisationProvider";
import { Montserrat } from "next/font/google";

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "TMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <OrganisationProvider>{children}</OrganisationProvider>
      </body>
    </html>
  );
}
